<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Kxy41Bb' shared service.

return $this->privates['.service_locator.Kxy41Bb'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repoNiveau' => function (): \App\Repository\NiveauRepository {
    return ($this->privates['App\Repository\NiveauRepository'] ?? $this->load('getNiveauRepositoryService.php'));
}));
