<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dsdYSe4' shared service.

return $this->privates['.service_locator.dsdYSe4'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repo' => function (): \App\Repository\DanseAppriseRepository {
    return ($this->privates['App\Repository\DanseAppriseRepository'] ?? $this->load('getDanseAppriseRepositoryService.php'));
}, 'repoCours' => function (): \App\Repository\CoursSupplementaireRepository {
    return ($this->privates['App\Repository\CoursSupplementaireRepository'] ?? $this->load('getCoursSupplementaireRepositoryService.php'));
}, 'repoMani' => function (): \App\Repository\ManifestationRepository {
    return ($this->privates['App\Repository\ManifestationRepository'] ?? $this->load('getManifestationRepositoryService.php'));
}, 'repoNiveau' => function (): \App\Repository\NiveauRepository {
    return ($this->privates['App\Repository\NiveauRepository'] ?? $this->load('getNiveauRepositoryService.php'));
}));
