<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zdqjeoC' shared service.

return $this->privates['.service_locator.zdqjeoC'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repo' => function (): \App\Repository\ManifestationRepository {
    return ($this->privates['App\Repository\ManifestationRepository'] ?? $this->load('getManifestationRepositoryService.php'));
}));
