<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AdminController::coursSuppCreate' => function () {
    return ($this->privates['.service_locator.j9GjiE_'] ?? $this->load('get_ServiceLocator_J9GjiEService.php'));
}, 'App\\Controller\\AdminController::coursSuppDelete' => function () {
    return ($this->privates['.service_locator.0AmQgoL'] ?? $this->load('get_ServiceLocator_0AmQgoLService.php'));
}, 'App\\Controller\\AdminController::danceCreate' => function () {
    return ($this->privates['.service_locator.jFJcUYi'] ?? $this->load('get_ServiceLocator_JFJcUYiService.php'));
}, 'App\\Controller\\AdminController::danceDelete' => function () {
    return ($this->privates['.service_locator.hfKl7sd'] ?? $this->load('get_ServiceLocator_HfKl7sdService.php'));
}, 'App\\Controller\\AdminController::dashboard' => function () {
    return ($this->privates['.service_locator.dsdYSe4'] ?? $this->load('get_ServiceLocator_DsdYSe4Service.php'));
}, 'App\\Controller\\AdminController::manifestationCreate' => function () {
    return ($this->privates['.service_locator.d9v.dkX'] ?? $this->load('get_ServiceLocator_D9v_DkXService.php'));
}, 'App\\Controller\\AdminController::manifestationDelete' => function () {
    return ($this->privates['.service_locator.Eg7WaGf'] ?? $this->load('get_ServiceLocator_Eg7WaGfService.php'));
}, 'App\\Controller\\AdminController::niveauCreate' => function () {
    return ($this->privates['.service_locator.wztvtmN'] ?? $this->load('get_ServiceLocator_WztvtmNService.php'));
}, 'App\\Controller\\AdminController::niveauDelete' => function () {
    return ($this->privates['.service_locator.LoFkyAw'] ?? $this->load('get_ServiceLocator_LoFkyAwService.php'));
}, 'App\\Controller\\PublicController::adherent' => function () {
    return ($this->privates['.service_locator.3bzNvzR'] ?? $this->load('get_ServiceLocator_3bzNvzRService.php'));
}, 'App\\Controller\\PublicController::danse' => function () {
    return ($this->privates['.service_locator.bp5RlZS'] ?? $this->load('get_ServiceLocator_Bp5RlZSService.php'));
}, 'App\\Controller\\PublicController::danseShow' => function () {
    return ($this->privates['.service_locator.6u2uzTr'] ?? $this->load('get_ServiceLocator_6u2uzTrService.php'));
}, 'App\\Controller\\PublicController::index' => function () {
    return ($this->privates['.service_locator.Kxy41Bb'] ?? $this->load('get_ServiceLocator_Kxy41BbService.php'));
}, 'App\\Controller\\PublicController::manifestation' => function () {
    return ($this->privates['.service_locator.zdqjeoC'] ?? $this->load('get_ServiceLocator_ZdqjeoCService.php'));
}, 'App\\Controller\\AdminController:coursSuppCreate' => function () {
    return ($this->privates['.service_locator.j9GjiE_'] ?? $this->load('get_ServiceLocator_J9GjiEService.php'));
}, 'App\\Controller\\AdminController:coursSuppDelete' => function () {
    return ($this->privates['.service_locator.0AmQgoL'] ?? $this->load('get_ServiceLocator_0AmQgoLService.php'));
}, 'App\\Controller\\AdminController:danceCreate' => function () {
    return ($this->privates['.service_locator.jFJcUYi'] ?? $this->load('get_ServiceLocator_JFJcUYiService.php'));
}, 'App\\Controller\\AdminController:danceDelete' => function () {
    return ($this->privates['.service_locator.hfKl7sd'] ?? $this->load('get_ServiceLocator_HfKl7sdService.php'));
}, 'App\\Controller\\AdminController:dashboard' => function () {
    return ($this->privates['.service_locator.dsdYSe4'] ?? $this->load('get_ServiceLocator_DsdYSe4Service.php'));
}, 'App\\Controller\\AdminController:manifestationCreate' => function () {
    return ($this->privates['.service_locator.d9v.dkX'] ?? $this->load('get_ServiceLocator_D9v_DkXService.php'));
}, 'App\\Controller\\AdminController:manifestationDelete' => function () {
    return ($this->privates['.service_locator.Eg7WaGf'] ?? $this->load('get_ServiceLocator_Eg7WaGfService.php'));
}, 'App\\Controller\\AdminController:niveauCreate' => function () {
    return ($this->privates['.service_locator.wztvtmN'] ?? $this->load('get_ServiceLocator_WztvtmNService.php'));
}, 'App\\Controller\\AdminController:niveauDelete' => function () {
    return ($this->privates['.service_locator.LoFkyAw'] ?? $this->load('get_ServiceLocator_LoFkyAwService.php'));
}, 'App\\Controller\\PublicController:adherent' => function () {
    return ($this->privates['.service_locator.3bzNvzR'] ?? $this->load('get_ServiceLocator_3bzNvzRService.php'));
}, 'App\\Controller\\PublicController:danse' => function () {
    return ($this->privates['.service_locator.bp5RlZS'] ?? $this->load('get_ServiceLocator_Bp5RlZSService.php'));
}, 'App\\Controller\\PublicController:danseShow' => function () {
    return ($this->privates['.service_locator.6u2uzTr'] ?? $this->load('get_ServiceLocator_6u2uzTrService.php'));
}, 'App\\Controller\\PublicController:index' => function () {
    return ($this->privates['.service_locator.Kxy41Bb'] ?? $this->load('get_ServiceLocator_Kxy41BbService.php'));
}, 'App\\Controller\\PublicController:manifestation' => function () {
    return ($this->privates['.service_locator.zdqjeoC'] ?? $this->load('get_ServiceLocator_ZdqjeoCService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
