<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hfKl7sd' shared service.

return $this->privates['.service_locator.hfKl7sd'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('da' => function (): \App\Entity\DanseApprise {
    return ($this->privates['.errored..service_locator.hfKl7sd.App\Entity\DanseApprise'] ?? $this->load('getDanseApprise2Service.php'));
}, 'manager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}, 'repo' => function (): \App\Repository\DanseAppriseRepository {
    return ($this->privates['App\Repository\DanseAppriseRepository'] ?? $this->load('getDanseAppriseRepositoryService.php'));
}));
