<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Eg7WaGf' shared service.

return $this->privates['.service_locator.Eg7WaGf'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('manager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}, 'mani' => function (): \App\Entity\Manifestation {
    return ($this->privates['.errored..service_locator.Eg7WaGf.App\Entity\Manifestation'] ?? $this->load('getManifestationService.php'));
}));
