<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3bzNvzR' shared service.

return $this->privates['.service_locator.3bzNvzR'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repo' => function (): \App\Repository\CoursSupplementaireRepository {
    return ($this->privates['App\Repository\CoursSupplementaireRepository'] ?? $this->load('getCoursSupplementaireRepositoryService.php'));
}));
