<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bp5RlZS' shared service.

return $this->privates['.service_locator.bp5RlZS'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repo' => function (): \App\Repository\DanseAppriseRepository {
    return ($this->privates['App\Repository\DanseAppriseRepository'] ?? $this->load('getDanseAppriseRepositoryService.php'));
}, 'repoNiveau' => function (): \App\Repository\NiveauRepository {
    return ($this->privates['App\Repository\NiveauRepository'] ?? $this->load('getNiveauRepositoryService.php'));
}));
