<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.0AmQgoL.App\Entity\CoursSupplementaire' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.0AmQgoL": it references class "App\\Entity\\CoursSupplementaire" but no such service exists.');
