<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.hfKl7sd.App\Entity\DanseApprise' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.hfKl7sd": it references class "App\\Entity\\DanseApprise" but no such service exists.');
