<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DanseApprise extends \App\Entity\DanseApprise implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'title', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'danceDate', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'youtubeLink', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'niveau', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'danseRevisees', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'brochure', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'imageFile'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'title', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'danceDate', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'youtubeLink', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'niveau', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'danseRevisees', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'brochure', '' . "\0" . 'App\\Entity\\DanseApprise' . "\0" . 'imageFile'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DanseApprise $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(?string $title): \App\Entity\DanseApprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDanceDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDanceDate', []);

        return parent::getDanceDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDanceDate(\DateTimeInterface $danceDate): \App\Entity\DanseApprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDanceDate', [$danceDate]);

        return parent::setDanceDate($danceDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getYoutubeLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYoutubeLink', []);

        return parent::getYoutubeLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setYoutubeLink(?string $youtubeLink): \App\Entity\DanseApprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYoutubeLink', [$youtubeLink]);

        return parent::setYoutubeLink($youtubeLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau(): ?\App\Entity\Niveau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(?\App\Entity\Niveau $niveau): \App\Entity\DanseApprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getDanseRevisees(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDanseRevisees', []);

        return parent::getDanseRevisees();
    }

    /**
     * {@inheritDoc}
     */
    public function addDanseRevisee(\App\Entity\DanseRevisee $danseRevisee): \App\Entity\DanseApprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDanseRevisee', [$danseRevisee]);

        return parent::addDanseRevisee($danseRevisee);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDanseRevisee(\App\Entity\DanseRevisee $danseRevisee): \App\Entity\DanseApprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDanseRevisee', [$danseRevisee]);

        return parent::removeDanseRevisee($danseRevisee);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrochure(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrochure', []);

        return parent::getBrochure();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrochure(?string $brochure): \App\Entity\DanseApprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrochure', [$brochure]);

        return parent::setBrochure($brochure);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$image]);

        return parent::setImageFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile(): ?\Symfony\Component\HttpFoundation\File\File
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

}
